# ----------------------------------------------
# Script Recorded by Ansys Electronics Desktop Version 2023.

# ----------------------------------------------
import ScriptEnv
ScriptEnv.Initialize("Ansoft.ElectronicsDesktop")
oDesktop.RestoreWindow()
oProject = oDesktop.SetActiveProject("Wide stop band BPF Modified export")
oDesign = oProject.SetActiveDesign("HFSSDesign2")
oDesign.ChangeProperty(
[
"NAME:AllTabs",
[
"NAME:LocalVariableTab",
[
"NAME:PropServers",
"LocalVariables"
],
[
"NAME:ChangedProps",
[
"NAME:b",
"Value:=" , "4mm"
]
]
]
])
oEditor = oDesign.SetActiveEditor("3D Modeler")
oEditor.ChangeProperty(
[
"NAME:AllTabs",
[
"NAME:Geometry3DCmdTab",
[
"NAME:PropServers",
"bpf1:CreateBox:1"
],
[
"NAME:ChangedProps",
[
"NAME:YSize",
"Value:=" , "14mm"
]
]
]
])
oEditor = oDesign.SetActiveEditor("3D Modeler")
oEditor.CreateBox(
[
"NAME:BoxParameters",
"XPosition:=" , "0mm",
"YPosition:=" , "0mm",
"ZPosition:=" , "0mm",
"XSize:=" , "-14mm",
"YSize:=" , "-29mm",
"ZSize:=" , "25mm"
],
[
"NAME:Attributes",
"Name:=" , "Box1",
"Flags:=" , "",
"Color:=" , "(143 175 143)",
"Transparency:=" , 0,
"PartCoordinateSystem:=", "Global",
"UDMId:=" , "",
"MaterialValue:=" , "\"vacuum\"",
"SurfaceMaterialValue:=", "\"\"",
"SolveInside:=" , True,
"ShellElement:=" , False,
"ShellElementThickness:=", "0mm",
"ReferenceTemperature:=", "20cel",
"IsMaterialEditable:=" , True,
"UseMaterialAppearance:=", False,
"IsLightweight:=" , False
])
oEditor = oDesign.SetActiveEditor("3D Modeler")
oEditor.ChangeProperty(
[
"NAME:AllTabs",
[
"NAME:Geometry3DCmdTab",
[
"NAME:PropServers",
"Box1:CreateBox:1"
],
[
"NAME:ChangedProps",
[
"NAME:Position",
"X:=" , "-5.65mm",
"Y:=" , "-16.725mm+l1+l2+l3+l4",
"Z:=" , "0mm"
]
]
]
])
oEditor.ChangeProperty(
[
"NAME:AllTabs",
[
"NAME:Geometry3DCmdTab",
[
"NAME:PropServers",
"Box1:CreateBox:1"
],
[
"NAME:ChangedProps",
[
"NAME:XSize",
"Value:=" , "11.3mm"
],
[
"NAME:YSize",
"Value:=" , "l5"
],
[
"NAME:ZSize",
"Value:=" , "0.003mm"
]
]
]
])
oEditor = oDesign.SetActiveEditor("3D Modeler")
oEditor.CreateBox(
[
"NAME:BoxParameters",
"XPosition:=" , "-9mm",
"YPosition:=" , "-28mm",
"ZPosition:=" , "0mm",
"XSize:=" , "7.5mm",
"YSize:=" , "6.775mm",
"ZSize:=" , "9mm"
],
[
"NAME:Attributes",
"Name:=" , "Box2",
"Flags:=" , "",
"Color:=" , "(143 175 143)",
"Transparency:=" , 0,
"PartCoordinateSystem:=", "Global",
"UDMId:=" , "",
"MaterialValue:=" , "\"vacuum\"",
"SurfaceMaterialValue:=", "\"\"",
"SolveInside:=" , True,
"ShellElement:=" , False,
"ShellElementThickness:=", "0mm",
"ReferenceTemperature:=", "20cel",
"IsMaterialEditable:=" , True,
"UseMaterialAppearance:=", False,
"IsLightweight:=" , False
])
oEditor = oDesign.SetActiveEditor("3D Modeler")
oEditor.ChangeProperty(
[
"NAME:AllTabs",
[
"NAME:Geometry3DCmdTab",
[
"NAME:PropServers",
"Box2:CreateBox:1"
],
[
"NAME:ChangedProps",
[
"NAME:Position",
"X:=" , "-0.214mm",
"Y:=" , "-16.725mm+l1+l2+l3+l4+l5",
"Z:=" , "0mm"
]
]
]
])
oEditor.ChangeProperty(
[
"NAME:AllTabs",
[
"NAME:Geometry3DCmdTab",
[
"NAME:PropServers",
"Box1:CreateBox:1"
],
[
"NAME:ChangedProps",
[
"NAME:XSize",
"Value:=" , "0.428mm"
],
[
"NAME:YSize",
"Value:=" , "l6"
]
]
]
])
oEditor.ChangeProperty(
[
"NAME:AllTabs",
[
"NAME:Geometry3DAttributeTab",
[
"NAME:PropServers",
"Box1"
],
[
"NAME:ChangedProps",
[
"NAME:Material",
"Value:=" , "\"copper\""
]
]
]
])
oEditor.ChangeProperty(
[
"NAME:AllTabs",
[
"NAME:Geometry3DAttributeTab",
[
"NAME:PropServers",
"Box2"
],
[
"NAME:ChangedProps",
[
"NAME:Material",
"Value:=" , "\"copper\""
]
]
]
])
oEditor.ChangeProperty(
[
"NAME:AllTabs",
[
"NAME:Geometry3DCmdTab",
[
"NAME:PropServers",
"Box2:CreateBox:1"
],
[
"NAME:ChangedProps",
[
"NAME:XSize",
"Value:=" , "0.428mm"
],
[
"NAME:YSize",
"Value:=" , "l6"
],
[
"NAME:ZSize",
"Value:=" , "0.003mm"
]
]
]
])
oModule = oDesign.GetModule("ModelSetup")
oModule.CreateOpenRegion(
[
"NAME:Settings",
"OpFreq:=" , "2.5GHz",
"Boundary:=" , "Radiation",
])
